Wordfly<- X17SeasonWordfly071817SO
#Rename loaded csv
head(Wordfly)
#See top rows of Wordfly
install.packages("tm")
library(tm)
#Take characters from Subject column amd create an object
subline<- paste(Wordfly$Subject, collapse="")
#Tansform object into a vector
subline_source<- VectorSource(subline)
#Clean vector object format/words
subjcorpus<- Corpus(subline_source)
subjcorpus<- tm_map(subjcorpus, content_transformer(tolower))
subjcorpus<- tm_map(subjcorpus, removePunctuation)
subjcorpus<- tm_map(subjcorpus, stripWhitespace)
subjcorpus<- tm_map(subjcorpus, removeWords, stopwords("english"))
stopwords("english")
#Start mapping of Stopwords
Filler<-stopwords("english")
Filler_source<- VectorSource(Filler)
Fillercorpus<- Corpus(Filler_source)
Fillercorpus<- tm_map(Fillercorpus, content_transformer(tolower))
Fillercorpus<- tm_map(Fillercorpus, removePunctuation)
Fillercorpus<- tm_map(Fillercorpus, stripWhitespace)
fwdtm<- DocumentTermMatrix(Fillercorpus)
fwdtm2<- as.matrix(fwdtm)
FWslfrequency<- colSums(fwdtm2)
FWslfrequency<- sort(FWslfrequency, decreasing=TRUE)
FWexamples<- names(FWslfrequency)
wordcloud(FWexamples[1:122], FWslfrequency[1:122])
warnings()
head(Filler, n=20)
write.csv(Filler, "FillerWords.csv")
#End mapping of Stopwords
asldtm<- DocumentTermMatrix(subjcorpus)
#Transform collection of cleaned words into a matrix
asldtm2<- as.matrix(asldtm)
aslfrequency<- colSums(asldtm2)
aslfrequency<- sort(aslfrequency, decreasing=TRUE)
#Show frequency of words
head(aslfrequency)
install.packages('wordcloud')
library(wordcloud)
aslwords<- names(aslfrequency)
#Create color scale
bleedscale<- colorRampPalette(c("pink", "red"))
bleedscale(10)
#Show color legend
plot(rep(1,10), col=bleedscale(10), pch=19, cex=3)
cryscale<- colorRampPalette(c("lightblue", "darkblue"))
cryscale(10)
plot(rep(1,10), col=cryscale(10), pch=19, cex=3)
#Plot Wordcloud
wordcloud(aslwords[1:100], aslfrequency[1:100])

Goodemail<- rbind2(Doubletake, Peek)
GEsubline<- paste(Goodemail$Subject, collapse="")
GEsubline_source<- VectorSource(GEsubline)
GEsubjcorpus<- Corpus(GEsubline_source)
GEsubjcorpus<- tm_map(GEsubjcorpus, content_transformer(tolower))
GEsubjcorpus<- tm_map(GEsubjcorpus, removePunctuation)
GEsubjcorpus<- tm_map(GEsubjcorpus, stripWhitespace)
GEsubjcorpus<- tm_map(GEsubjcorpus, removeWords, stopwords("english"))
GEsldtm<- DocumentTermMatrix(GEsubjcorpus)
GEsldtm2<- as.matrix(GEsldtm)
GEslfrequency<- colSums(GEsldtm2)
GEslfrequency<- sort(GEslfrequency, decreasing=TRUE)
#Display table results
head(GEslfrequency, n = 50)
#Wordcloud color coded by frequency
wordcloud(GEslwords[1:50], GEslfrequency[1:50], col=bleedscale(10))
#Export to CSV file in Documents folder
write.csv(GEslfrequency, "GEslfrequency.csv")

BadEC<- rbind2(ECQ==1,ECQ==2, ECQ==3)
Bademail<- subset(Wordfly, BadEC)
BEsubline<- paste(Bademail$Subject, collapse="")
BEsubline_source<- VectorSource(BEsubline)
BEsubjcorpus<- Corpus(BEsubline_source)
BEsubjcorpus<- tm_map(BEsubjcorpus, content_transformer(tolower))
BEsubjcorpus<- tm_map(BEsubjcorpus, removePunctuation)
BEsubjcorpus<- tm_map(BEsubjcorpus, stripWhitespace)
BEsubjcorpus<- tm_map(BEsubjcorpus, removeWords, stopwords("english"))
BEsldtm<- DocumentTermMatrix(BEsubjcorpus)
BEsldtm2<- as.matrix(BEsldtm)
BEslfrequency<- colSums(BEsldtm2)
BEslfrequency<- sort(BEslfrequency, decreasing=TRUE)
head(BEslfrequency, n = 50)
BEslwords<- names(BEslfrequency)
wordcloud(BEslwords[1:50], BEslfrequency[1:50], col=cryscale(10))
write.csv(BEslfrequency, "BEslfrequency.csv")

WNOge<- rbind2(WNODouble, WNOPeek)
WNOgsl<- paste(WNOge$Subject, collapse="")
WNOgsl_source<- VectorSource(WNOgsl)
WNOgslcorpus<- Corpus(WNOgsl_source)
WNOgslcorpus<- tm_map(WNOgslcorpus, content_transformer(tolower))
WNOgslcorpus<- tm_map(WNOgslcorpus, removePunctuation)
WNOgslcorpus<- tm_map(WNOgslcorpus, stripWhitespace)
WNOgslcorpus<- tm_map(WNOgslcorpus, removeWords, stopwords("english"))
WNOgsldtm<- DocumentTermMatrix(WNOgslcorpus)
WNOgsldtm2<- as.matrix(WNOgsldtm)
WNOgslfrequency<- colSums(WNOgsldtm2)
WNOgslfrequency<- sort(WNOgslfrequency, decreasing=TRUE)
head(WNOgslfrequency)
WNOgslwords<- names(WNOgslfrequency)
wordcloud(WNOgslwords[1:50], WNOgslfrequency[1:50], col=bleedscale(10))
write.csv(WNOgslfrequency, "WNOgslfreqeuncy.csv")

WNObec<- rbind2(WNOC==1, WNOC==4, WNOC==5)
WNObe<- subset(Opera, WNObec)
WNObsl<- paste(WNObe$Subject, collapse="")
WNObsl_source<- VectorSource(WNObsl)
WNObslcorpus<- Corpus(WNObsl_source)
WNObslcorpus<- tm_map(WNObslcorpus, content_transformer(tolower))
WNObslcorpus<- tm_map(WNObslcorpus, removePunctuation)
WNObslcorpus<- tm_map(WNObslcorpus, stripWhitespace)
WNObslcorpus<- tm_map(WNObslcorpus, removeWords, stopwords("english"))
WNObsldtm<- DocumentTermMatrix(WNObslcorpus)
WNObsldtm2<- as.matrix(WNObsldtm)
WNObslfrequency<- colSums(WNObsldtm2)
WNObslfrequency<- sort(WNObslfrequency, decreasing=TRUE)
head(WNObslfrequency)
WNObslwords<- names(WNObslfrequency)
wordcloud(WNObslwords[1:50], WNObslfrequency[1:50], col=cryscale(10))
write.csv(WNObslfrequency, "WNObslfrequency.csv")

Stephge<- rbind2(StephDouble, StephPeek)
Stephgsl<- paste(Stephge$Subject, collapse="")
Stephgsl_source<- VectorSource(Stephgsl)
Stephgslcorpus<- Corpus(Stephgsl_source)
Stephgslcorpus<- tm_map(Stephgslcorpus, content_transformer(tolower))
Stephgslcorpus<- tm_map(Stephgslcorpus, removePunctuation)
Stephgslcorpus<- tm_map(Stephgslcorpus, stripWhitespace)
Stephgslcorpus<- tm_map(Stephgslcorpus, removeWords, stopwords("english"))
Stephgsldtm<- DocumentTermMatrix(Stephgslcorpus)
Stephgsldtm2<- as.matrix(Stephgsldtm)
Stephgslfrequency<- colSums(Stephgsldtm2)
Stephgslfrequency<- sort(Stephgslfrequency, decreasing=TRUE)
head(Stephgslfrequency, n = 20)
Stephgslwords<- names(Stephgslfrequency)
wordcloud(Stephgslwords[1:20], Stephgslfrequency[1:20], col=bleedscale(10))
write.csv(Stephgslfrequency, "Stepgslfrequency.csv")

Stephbec<- rbind2(ADSC==2, ADSC==3, ADSC==5)
Stephbe<- subset(Steph, Stephbec)
Stephbsl<- paste(Stephbe$Subject, collapse="")
Stephbsl_source<- VectorSource(Stephbsl)
Stephbslcorpus<- Corpus(Stephbsl_source)
Stephbslcorpus<- tm_map(Stephbslcorpus, content_transformer(tolower))
Stephbslcorpus<- tm_map(Stephbslcorpus, removePunctuation)
Stephbslcorpus<- tm_map(Stephbslcorpus, stripWhitespace)
Stephbslcorpus<- tm_map(Stephbslcorpus, removeWords, stopwords("english"))
Stephbsldtm<- DocumentTermMatrix(Stephbslcorpus)
Stephbsldtm2<- as.matrix(Stephbsldtm)
Stephbslfrequency<- colSums(Stephbsldtm2)
Stephbslfrequency<- sort(Stephbslfrequency, decreasing=TRUE)
head(Stephbslfrequency, n = 20)
Stephbslwords<- names(Stephbslfrequency)
wordcloud(Stephbslwords[1:20], Stephbslfrequency[1:20], col=cryscale(10))
write.csv(Stephbslfrequency, "Stephbslfrequency.csv")

Derekge<- rbind2(DerekDouble, DerekPeek)
Derekgsl<- paste(Derekge$Subject, collapse="")
Derekgsl_source<- VectorSource(Derekgsl)
Derekgslcorpus<- Corpus(Derekgsl_source)
Derekgslcorpus<- tm_map(Derekgslcorpus, content_transformer(tolower))
Derekgslcorpus<- tm_map(Derekgslcorpus, removePunctuation)
Derekgslcorpus<- tm_map(Derekgslcorpus, stripWhitespace)
Derekgslcorpus<- tm_map(Derekgslcorpus, removeWords, stopwords("english"))
Derekgsldtm<- DocumentTermMatrix(Derekgslcorpus)
Derekgsldtm2<- as.matrix(Derekgsldtm)
Derekgslfrequency<- colSums(Derekgsldtm2)
Derekgslfrequency<- sort(Derekgslfrequency, decreasing=TRUE)
head(Derekgslfrequency, n = 20)
Derekgslwords<- names(Derekgslfrequency)
wordcloud(Derekgslwords[1:50], Derekgslfrequency[1:50], col=bleedscale(10))
write.csv(Derekgslfrequency, "Derekgslfrequency.csv")

Derekbec<- rbind2(DOGC==2, DOGC==3, DOGC==4)
Derekbe<- subset(Derek, Derekbec)
Derekbsl<- paste(Derekbe$Subject, collapse="")
Derekbsl_source<- VectorSource(Derekbsl)
Derekbslcorpus<- Corpus(Derekbsl_source)
Derekbslcorpus<- tm_map(Derekbslcorpus, content_transformer(tolower))
Derekbslcorpus<- tm_map(Derekbslcorpus, removePunctuation)
Derekbslcorpus<- tm_map(Derekbslcorpus, stripWhitespace)
Derekbslcorpus<- tm_map(Derekbslcorpus, removeWords, stopwords("english"))
Derekbsldtm<- DocumentTermMatrix(Derekbslcorpus)
Derekbsldtm2<- as.matrix(Derekbsldtm)
Derekbslfrequency<- colSums(Derekbsldtm2)
Derekbslfrequency<- sort(Derekbslfrequency, decreasing=TRUE)
head(Derekbslfrequency, n=20)
Derekbslwords<- names(Derekbslfrequency)
wordcloud(Derekbslwords[1:50], Derekbslfrequency[1:50], col=cryscale(10))
write.csv(Derekbslfrequency, "Derekbslfrequency.csv")

Theaterge<- rbind2(TheaterDouble, TheaterPeek)
Theatergsl<- paste(Theaterge$Subject, collapse="")
Theaterslcorpus<- VectorSource(Theatergsl)
Theaterslcorpus<- Corpus(Theaterslcorpus)
Theaterslcorpus<- tm_map(Theaterslcorpus, content_transformer(tolower))
Theaterslcorpus<- tm_map(Theaterslcorpus, removePunctuation)
Theaterslcorpus<- tm_map(Theaterslcorpus, stripWhitespace)
Theaterslcorpus<- tm_map(Theaterslcorpus, removeWords, stopwords("english"))
Theatergsldtm<- DocumentTermMatrix(Theaterslcorpus)
Theatergsldtm2<- as.matrix(Theatergsldtm)
Theatergslfrequency<- colSums(Theatergsldtm2)
Theatergslfrequency<- sort(Theatergslfrequency, decreasing=TRUE)
head(Theatergslfrequency, n=20)
Theatergslwords<- names(Theatergslfrequency)
wordcloud(Theatergslwords[1:50], Theatergslfrequency[1:50], col=bleedscale(10))
write.csv(Theatergslfrequency, "Theatergslfrequency.csv")

Theaterbec<- rbind2(TTC==1, TTC==4, TTC==5)
Theaterbe<- subset(Theater, Theaterbec)
Theaterbsl<- paste(Theaterbe$Subject, collapse="")
Theaterbsl_source<- VectorSource(Theaterbsl)
Theaterbslcorpus<- Corpus(Theaterbsl_source)
Theaterbslcorpus<- tm_map(Theaterbslcorpus, content_transformer(tolower))
Theaterbslcorpus<- tm_map(Theaterbslcorpus, removePunctuation)
Theaterbslcorpus<- tm_map(Theaterbslcorpus, stripWhitespace)
Theaterbslcorpus<- tm_map(Theaterbslcorpus, removeWords, stopwords("english"))
Theaterbsldtm<- DocumentTermMatrix(Theaterbslcorpus)
Theaterbsldtm2<- as.matrix(Theaterbsldtm)
Theaterbslfrequency<- colSums(Theaterbsldtm2)
Theaterbslfrequency<- sort(Theaterbslfrequency, decreasing=TRUE)
head(Theaterbslfrequency, n=20)
Theaterbslwords<- names(Theaterbslfrequency)
wordcloud(Theaterbslwords[1:50], Theaterbslfrequency[1:50], col=cryscale(10))
write.csv(Theaterbslfrequency, "Theaterbslfrequency.csv")
